import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { NavLink } from 'react-router-dom';
import { ROLE_LABEL, formatDate, weekdayLabel } from '../lib/format.ts';
import { USE_MOCK } from '../lib/api.ts';
export function AppShell({ session, items, title, subtitle, actions, today, onSignOut, children, }) {
    const groups = [...new Set(items.map((item) => item.group))];
    return (_jsxs("div", { className: "shell", children: [_jsxs("aside", { className: "sidebar", children: [_jsxs("div", { className: "brand", children: [_jsx("div", { className: "brand__mark", "aria-hidden": "true", children: "CARE" }), _jsxs("div", { children: [_jsx("div", { className: "brand__name", children: "C.A.R.E. System" }), _jsx("div", { className: "brand__sub", children: "\u884C\u70BA\u53CD\u601D\u8207\u8FFD\u8E64" })] })] }), _jsx("nav", { className: "nav", "aria-label": "\u4E3B\u5C0E\u89BD", children: groups.map((group) => (_jsxs("div", { children: [_jsx("div", { className: "nav__group", children: group }), items
                                    .filter((item) => item.group === group)
                                    .map((item) => (_jsxs(NavLink, { to: item.to, className: ({ isActive }) => `nav__item${isActive ? ' nav__item--active' : ''}`, children: [_jsx("span", { "aria-hidden": "true", children: item.icon }), _jsx("span", { children: item.label }), item.badge ? _jsx("span", { className: "nav__badge", children: item.badge }) : null] }, item.to)))] }, group))) }), _jsxs("div", { className: "sidebar__footer", children: [_jsxs("div", { children: [_jsx("strong", { children: session.name }), _jsx("div", { children: session.roles.map((role) => ROLE_LABEL[role] ?? role).join('・') })] }), USE_MOCK && _jsx("div", { className: "badge badge--warning", children: "\u793A\u7BC4\u6A21\u5F0F\uFF08\u6A21\u64EC\u8CC7\u6599\uFF09" }), _jsx("button", { className: "btn btn--ghost", onClick: onSignOut, style: { justifyContent: 'flex-start', padding: 0 }, children: "\u767B\u51FA" })] })] }), _jsxs("div", { className: "main", children: [_jsxs("header", { className: "topbar", children: [_jsxs("div", { children: [_jsx("h1", { className: "topbar__title", children: title }), subtitle && _jsx("div", { className: "topbar__meta", children: subtitle })] }), _jsx("span", { className: "topbar__spacer" }), _jsxs("div", { className: "topbar__meta", children: [formatDate(today), "\uFF08", weekdayLabel(today), "\uFF09"] }), actions] }), _jsx("main", { className: "content", children: children })] })] }));
}
